import type { Metadata } from "next";
import { cn } from "@/lib/cn";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "bg-neutral-950 text-neutral-50 min-h-screen"
        )}
      >
        {children}
      </body>
    </html>
  );
}
